#!/usr/bin/env python3
"""Make ui/fonts.c: the OS's two text fonts, from Source Code Pro.

    python3 tools/fontgen.py SourceCodePro-Medium.ttf > ui/fonts.c

Needs Pillow (pip install pillow). Source Code Pro is Adobe's, under
the SIL Open Font License 1.1 (see ui/fonts-LICENSE.txt); get it from
https://github.com/adobe-fonts/source-code-pro (release branch, TTF/).

Two monospaced sizes, as the calculator's own software uses: small,
7x14 pixels a character, and large, 10x18. Each pixel is a 4-bit
coverage value (0 = background, 15 = text colour), so the display can
blend the edges smoothly. Characters: ASCII 32..126.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONTS = [  # name, cell width, cell height, size in pixels
    ("small", 7, 14, 11.5),
    ("large", 10, 18, 16.5),
]
CHARS = [chr(c) for c in range(32, 127)]


def baseline_for(font, h):
    """The baseline that centres the tallest and deepest glyphs in the cell."""
    top = min(font.getbbox(c, anchor="ls")[1] for c in CHARS if c.strip())
    bottom = max(font.getbbox(c, anchor="ls")[3] for c in CHARS if c.strip())
    return round((h - (bottom - top)) / 2 - top)


def render(font, w, h, base, c):
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((w / 2, base), c, fill=255, font=font, anchor="ms")
    return [[(img.getpixel((x, y)) * 15 + 127) // 255 for x in range(w)] for y in range(h)]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    out = ["/* Generated by tools/fontgen.py from Source Code Pro (Adobe, SIL Open",
           " * Font License 1.1: ui/fonts-LICENSE.txt). Don't edit; run the script. */",
           '#include "../hal/font.h"', ""]
    for name, w, h, size in FONTS:
        font = ImageFont.truetype(sys.argv[1], size)
        base = baseline_for(font, h)
        row = (w + 1) // 2
        out.append(f"static const uint8_t {name}_data[{len(CHARS)} * {h} * {row}] = {{")
        for c in CHARS:
            px = render(font, w, h, base, c)
            data = []
            for y in range(h):
                for x in range(0, w, 2):
                    hi = px[y][x]
                    lo = px[y][x + 1] if x + 1 < w else 0
                    data.append(hi << 4 | lo)
            label = "' '" if c == " " else repr(c)
            out.append(f"    /* {label} */ " + ",".join(f"0x{b:02x}" for b in data) + ",")
        out.append("};")
        out.append(f"const font_t font_{name} = {{ {w}, {h}, {name}_data }};")
        out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
