#!/usr/bin/env python3
"""Make ui/icons.c: the home screen's app icons, 55 x 56 pixels.

    python3 tools/icongen.py SourceCodePro-Semibold.ttf > ui/icons.c

Needs Pillow. Each icon is drawn at four times the size and scaled
down, so its edges are smooth, on the white of the home screen. They
are stored run-length coded in RGB565: (count, colour) pairs.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

W, H, S = 55, 56, 4                      # size, and the scale they are drawn at
YELLOW, DARK, SLATE = (255, 183, 52), (65, 65, 71), (78, 83, 94)
LIGHT, LIGHTER, WHITE = (226, 228, 232), (240, 241, 243), (255, 255, 255)
GREY = (150, 154, 162)


def tile(d, colour):
    """The rounded square every icon sits on, with a soft lower edge"""
    shade = tuple(max(0, c - 28) for c in colour)
    d.rounded_rectangle([2 * S, 3 * S, 53 * S, 55 * S], 11 * S, fill=shade)
    d.rounded_rectangle([2 * S, 1 * S, 53 * S, 53 * S], 11 * S, fill=colour)


def text(d, font, size, xy, s, colour, anchor="mm"):
    d.text((xy[0] * S, xy[1] * S), s, fill=colour, font=ImageFont.truetype(font, size * S), anchor=anchor)


def box(d, x0, y0, x1, y1, colour, r=2):
    d.rounded_rectangle([x0 * S, y0 * S, x1 * S, y1 * S], r * S, fill=colour)


def line(d, pts, colour, width):
    d.line([(x * S, y * S) for x, y in pts], fill=colour, width=int(width * S), joint="curve")


def calculation(d, f):
    tile(d, LIGHT)
    box(d, 9, 8, 46, 21, WHITE, 3)
    text(d, f, 10, (27.5, 14.5), "1+2", DARK)
    for i in range(3):
        for j in range(2):
            box(d, 9 + i * 13, 25 + j * 12, 20 + i * 13, 34 + j * 12, YELLOW if (i, j) == (2, 1) else SLATE)


def functions(d, f):
    import math
    tile(d, LIGHTER)
    line(d, [(10, 27), (46, 27)], GREY, 1.6)
    line(d, [(15, 9), (15, 46)], GREY, 1.6)
    pts = [(9 + t * 0.4, 27 - 13 * math.sin((t - 6) / 13.5)) for t in range(0, 93)]
    line(d, pts, YELLOW, 4.2)


def equations(d, f):
    tile(d, SLATE)
    text(d, f, 19, (21, 27), "x", YELLOW)
    text(d, f, 17, (37, 27.5), "=?", WHITE)


def statistics(d, f):
    tile(d, LIGHT)
    for i, h in enumerate([14, 24, 31, 20]):
        box(d, 10 + i * 9.5, 44 - h, 17 + i * 9.5, 44, SLATE, 1.5)
    line(d, [(8, 22), (47, 22)], YELLOW, 3)


def python(d, f):
    tile(d, SLATE)
    text(d, f, 11, (10, 15), ">>>", YELLOW, "lm")
    for i, w in enumerate([30, 22, 26]):
        box(d, 10, 24 + i * 7.5, 10 + w, 27.5 + i * 7.5, WHITE, 1.5)


def files(d, f):
    tile(d, LIGHT)
    box(d, 9, 14, 26, 22, (232, 160, 30), 3)
    box(d, 9, 18, 46, 43, YELLOW, 3)
    box(d, 9, 25, 46, 43, (255, 196, 92), 3)


def editor(d, f):
    tile(d, LIGHT)
    box(d, 12, 7, 43, 47, WHITE, 3)
    for i, w in enumerate([24, 19, 22, 14]):
        box(d, 16, 13 + i * 8, 16 + w, 15.5 + i * 8, GREY, 1)
    box(d, 31, 36, 33.5, 44, YELLOW, 1)


def shell(d, f):
    tile(d, DARK)
    text(d, f, 15, (11, 27), ">", WHITE, "lm")
    box(d, 25, 32, 42, 35.5, YELLOW, 1)


def games(d, f):
    tile(d, YELLOW)
    c = 8.5
    for x, y in [(0, 0), (1, 0), (2, 0), (2, 1)]:       # an L of four blocks
        box(d, 10 + x * c, 14 + y * c, 10 + x * c + c - 1.5, 14 + y * c + c - 1.5, DARK, 1.5)
    for x, y in [(1, 2), (2, 2), (1, 3), (2, 3)]:       # and a square
        box(d, 15 + x * c, 14 + y * c, 15 + x * c + c - 1.5, 14 + y * c + c - 1.5, WHITE, 1.5)


def help_(d, f):
    tile(d, LIGHT)
    d.ellipse([12 * S, 9 * S, 43 * S, 40 * S], fill=YELLOW)
    text(d, f, 22, (27.5, 25), "?", DARK)
    box(d, 17, 44, 38, 46.5, GREY, 1)


def settings(d, f):
    tile(d, SLATE)
    for i, k in enumerate([0.65, 0.3, 0.55]):
        y = 15 + i * 11
        line(d, [(11, y), (44, y)], (190, 194, 202), 2.2)
        cx = 11 + k * 33
        d.ellipse([(cx - 4) * S, (y - 4) * S, (cx + 4) * S, (y + 4) * S], fill=YELLOW)


ICONS = [("calculation", calculation), ("functions", functions), ("equations", equations),
         ("statistics", statistics), ("python", python), ("files", files), ("editor", editor),
         ("shell", shell), ("games", games), ("help", help_), ("settings", settings)]


def rgb565(p):
    r, g, b = p[:3]
    return (r >> 3) << 11 | (g >> 2) << 5 | b >> 3


def main():
    if len(sys.argv) not in (2, 3):
        sys.exit(__doc__)
    font = sys.argv[1]
    out = ["/* Generated by tools/icongen.py. Don't edit; run the script. */",
           '#include "icons.h"', ""]
    sheet = Image.new("RGB", (W * len(ICONS), H), WHITE)
    for n, (name, draw) in enumerate(ICONS):
        big = Image.new("RGB", (W * S, H * S), WHITE)
        draw(ImageDraw.Draw(big), font)
        img = big.resize((W, H), Image.LANCZOS)
        sheet.paste(img, (n * W, 0))
        px = [rgb565(img.getpixel((x, y))) for y in range(H) for x in range(W)]
        runs, i = [], 0
        while i < len(px):
            j = i
            while j < len(px) and px[j] == px[i] and j - i < 0xFFFF:
                j += 1
            runs += [j - i, px[i]]
            i = j
        out.append(f"static const uint16_t {name}_rle[] = {{")
        for k in range(0, len(runs), 16):
            out.append("    " + ",".join(f"0x{v:04x}" for v in runs[k:k + 16]) + ",")
        out.append("};")
        out.append(f"const icon_t icon_{name} = {{ {len(runs) // 2}, {name}_rle }};")
        out.append("")
    if len(sys.argv) == 3:
        sheet.resize((sheet.width * 3, sheet.height * 3), Image.NEAREST).save(sys.argv[2])
    print("\n".join(out))


if __name__ == "__main__":
    main()
